### ISSUE TITLE
Problem with EPSG:2154 and TMS layer

### ISSUE THREAD

**Issue by mgageo** [kartena/Proj4Leaflet#104]
Hello,
With leaflet 0.7.7, I try to display a TMS layer http://mga.alwaysdata.net/leaflet/exemples/tms_l93.html
The url of the tiles have a negative number for y 
http://geobretagne.fr/gwc02/service/tms/1.0.0/satellite-ancien@EPSG%3A2154@png/7/3084/-1428.png

It's a bug from the server or from my transciption ?
cf http://geobretagne.fr/gwc02/service/tms/1.0.0/satellite-ancien@EPSG%3A2154@png

Thank's for the help

**Comment by mgageo** [comment]
Hi,

I try with a wms layer and leaflet v1.0.0-beta.2 and refactor : http://mga.alwaysdata.net/leaflet/exemples/wms_gb_l93.html

There is some thing wrong with origin ?

**Comment by perliedman** [comment]
I'm going to close this as it's been too long, so it's really hard to tell what the issue might be.

If you still have the same issue with latest Leaflet and latest Proj4Leaflet, we can consider reopening and having a look.
