### ISSUE TITLE
Unknown projection stere

### ISSUE THREAD

**Issue by dzNavitski** [kartena/Proj4Leaflet#105]
Hello!

I try to use EPSG:3995 projection (http://epsg.io/3995). 
But Proj4Leaflet throws error: 'Uncaught unknown projection stere'.

**Comment by perliedman** [comment]
Hi!

It sounds like this is rather an issue with [Proj4js](https://github.com/proj4js/proj4js) than Proj4Leaflet. 

Proj4Leaflet is more or less a wrapper around Proj4js that adapts its functionality for Leaflet, the actual projection code and handling of projection parameters is done by Proj4js.

A quick look at the [projections supported by Proj4js](https://github.com/proj4js/proj4js/tree/master/lib/projections) does include `stere` - might it be that you're using an old version of Proj4js? (For example, the one currently included in Proj4Leaflet is quite old, AFAIK).

**Comment by dzNavitski** [comment]
Thanks, you are right)
