### ISSUE TITLE
L.Proj.CRS is missing distance method

### ISSUE THREAD

**Issue by perliedman** [kartena/Proj4Leaflet#109]
In Leaflet 1.0, a CRS is expected to implement the method `distance`, which calculates the distance between two `L.LatLng`s, see [L.CRS.Earth](https://github.com/Leaflet/Leaflet/blob/master/src/geo/crs/CRS.Earth.js#L11) for example.

I think the easy and "correct enough" fix is to just set `L.Proj.CRS.distance = L.CRS.Earth.distance`, which will use the haversine formula for all projections.

An alternative, more complicated, but at least in some sense more correct solution, which uses the fact that distances are preserved by some projections, would be to project each LatLng, finding the differences _dx_ and _dy_ and doing `d = Math.sqrt(dx*dx+dy*dy)`, but some problems need to be solved:
- This doesn't apply to _all_ projections, both EPSG:3857 and EPSG:4326 can for example be used with Proj4Leaflet, where this is not true, just to give an example.
- Some projections where this is true still use weird units, like feet, and the result must be scaled so that `distance` still returns its result in meters

I'd vote for just using `L.CRS.Earth.distance` until we find some use case were it would cause a problem.

**Comment by emacgillavry** [comment]
Updated the gist http://bl.ocks.org/emacgillavry/1a654b76d35deceb9bec. The scalebar does appear and no error message. However, I simply get the stock image it seems: no lengths indicated. Am I missing something?

**Comment by perliedman** [comment]
Yeah, `L.CRS.Earth.distance` uses a constant, `R`, which it expects to be part of `this`, which it isn't with my hack.

Again, this is super-ugly, but works as a workaround:

```
RD.distance = L.CRS.Earth.distance;
RD.R = 6378137;
```

**Comment by emacgillavry** [comment]
Updated the gist and it works beatifully. Have added 100 meter grid layer
as a reference. Thank you very much for looking into this.

**Comment by sivesind** [comment]
Any hope of fixing this? It holds back the release of a branch compatible with leaflet 1.0.0 beta, #90.

**Comment by pthorin** [comment]
Closed in #126.
