### ISSUE TITLE
Problem configuring EPSG:3812 TMS map

### ISSUE THREAD

**Issue by pieterprovoost** [kartena/Proj4Leaflet#112]
This is a support request, if you have time. I'm trying to use `L.Proj.CRS.TMS`, but the tile numbers are off. I'm currently getting tiles in the range of `7/27/7`, but I should be more like `7/6084/5306`. `origin` or `transformation` appear to have no effect.

```javascript
// http://ccff02.minfin.fgov.be/cadgisweb/
// http://ccff02.minfin.fgov.be/cadgisservices/A/InternetViewer/MapServer
// http://ccff02.minfin.fgov.be/cadgisservices/A/InternetViewer/MapServer/tile/7/6084/5306

var crs = new L.Proj.CRS.TMS("EPSG:3812", "+proj=lcc +lat_1=49.83333333333334 +lat_2=51.16666666666666 +lat_0=50.797815 +lon_0=4.359215833333333 +x_0=649328 +y_0=665262 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
	[517579.6608, 523633.8376, 797118.5854, 745328.5980],
	{
		resolutions: [ 396.87579375158754, 264.5838625010584, 132.2919312505292, 66.1459656252646, 39.687579375158755, 26.458386250105836, 19.843789687579378, 13.229193125052918, 6.614596562526459, 2.6458386250105836, 1.3229193125052918, 0.6614596562526459, 0.26458386250105836, 0.13229193125052918 ]
	});

var map = new L.Map("map", {
	crs: crs,
	continuousWorld: true
}).setView([51.2108, 3.2259], 7);

new L.TileLayer('http://ccff02.minfin.fgov.be/cadgisservices/A/InternetViewer/MapServer/tile/{z}/{y}/{x}', {
	minZoom: 0,
	maxZoom: 13,
	continuousWorld: true,
	tms: true,
	tileSize: 512
}).addTo(map);
```

Thanks!

**Comment by pieterprovoost** [comment]
Solved by setting projectedBounds[0] and projectedBounds[3] to origin[0] and origin[1].

**Comment by perliedman** [comment]
@pieterprovoost do you mean you manually had to set `projectedBounds`? That sounds like a potential issue with Proj4Leaflet, you should never have to touch that (in fact, it should probably be named `_projectedBounds` to make clear it's not part of the public API).

As usual, a fiddle illustrating the problem would be most welcome.

**Comment by pieterprovoost** [comment]
@perliedman I modified the projectedBounds parameter after finding this:

```
options.origin = [projectedBounds[0], projectedBounds[3]]
```

I guess my initial configuration based on [this](http://ccff02.minfin.fgov.be/cadgisservices/A/InternetViewer/MapServer) was just wrong.

Fiddle: https://jsfiddle.net/6ortmjne/

**Comment by perliedman** [comment]
@pieterprovoost ah, ok, I see.

You're fiddle looks like I would expect it to. Good to hear that you resolved it, and thanks for sharing your code!
