### ISSUE TITLE
BSD-2-Clause or MIT license?

### ISSUE THREAD

**Issue by maruilian11** [kartena/Proj4Leaflet#114]
hi, recently we want to add your lib on https://cdnjs.com, i saw `BSD-2-Clause` license in your [LICENSE](https://github.com/kartena/Proj4Leaflet/blob/master/LICENSE) but `MIT` in your [package.json](https://github.com/kartena/Proj4Leaflet/blob/master/package.json#L34). just want to confirm this with you.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/7075

**Comment by perliedman** [comment]
Closed by 0a2a65bccbd8bce85917a4add1481da7aa9a4f59 and dcbfd4531428a21a0de8e840c6a2e758587e5b5f
