### ISSUE TITLE
Layer transformation with different view projection and layer projection

### ISSUE THREAD

**Issue by idreamussr** [kartena/Proj4Leaflet#115]
I try to display several layers in own projections on base map also in it's own projection

Below my working example  implemented using OpenLayers + proj4 library 

```javascript
var projection_name = 'EPSG:32610';
proj4.defs(projection_name, "+proj=utm +zone=10 +datum=WGS84 +units=m +no_defs");
var proj = ol.proj.get(projection_name);
var my_custom_layer = new ol.layer.Tile({
        opacity: 0.5,
        source: new ol.source.XYZ({
            url: '<zxy_tile_server_url>',
            projection: proj,
        })
    });

var osm_layer = new ol.layer.Tile({
    source: new ol.source.MapQuest({layer: 'osm'}),
    opacity: 0.3
});

with OpenLayers I can create something like this
var map = new ol.Map({
    layers: [osm_layer, my_custom_layer],
    target: 'map',
    view: new ol.View({
        projection: 'EPSG:4326',
        center: [-122.347, 37.805],
        zoom: 9
    })
});
```

And as result will be rendered map in projection 4326 and layer in another projection (epsg:32610).
Each tile of my_custom_layer will be transformed its figure to fit for base map projection.
So my tile server every time returns simple square (256x256) tile and OL will transform square to some new figure.

Is it possible to implement it using Leaflet + Proj4Leaflet?

**Comment by semone** [comment]
If I understand your question correct you want to have one base tile layer and other tile layers in other projections in the same map? 

I think this does not work in Leaflet since you set the CRS on the map layer and all tile layers must have that same CRS.

**Comment by perliedman** [comment]
Indeed.

Also see http://stackoverflow.com/questions/36036347/proj4leaflet-reprojection-like-in-openlayers/36042745#36042745 for an alternative answer to the same question.

**Comment by idreamussr** [comment]
semone, yep You're right understand me. 
My goal  - transform some tile bitmap to new figure on client side. 
Openlayers has this feature. And i spend a lof of time to find it in leaflet.
This functionality fully described here
http://openlayers.org/en/v3.14.2/doc/tutorials/raster-reprojection.html.

Is it possible to make some plugin for leaflet ?

**Comment by perliedman** [comment]
There's no such plugin I'm aware of.

The closest thing I'm aware of is https://github.com/publiclab/Leaflet.DistortableImage, but it's not specifically oriented towards reprojection, and not for a complete tile layer. Having said that, it might be possible to use the same technology for what you want, but you'd have to code it up yourself.

I'd also recommend thinking about if you _really_ want raster reprojection. I'd say it's a last resort, rather than a general solution. I'd recommend reading this (fairly old) post, under the section "Your Raster Projections Aren’t Going to Work": http://www.macwright.org/2012/01/12/openlayers.html - sure, OpenLayers 3 can do this, but the spirit of the argument still holds.

**Comment by zhen1991** [comment]
Hi!
Does any one know why my map does look like that ??
![skarmbild 1](https://user-images.githubusercontent.com/37370847/38353816-f5b9076a-38b7-11e8-948d-fadfa5664170.png)
thnx :)

**Comment by zhen1991** [comment]
The code is next to the view is the same code i am runing and getting this:(

**Comment by perliedman** [comment]
@zhen1991 hi there. I fail to see how the problem you're reporting relate to this issue - please don't just add comments to random issue, it creates a lot of noise for others.

**Comment by zhen1991** [comment]
OK
