### ISSUE TITLE
leaflet-proj-refactor requires the wrong leaflet version

### ISSUE THREAD

**Issue by dannybloe** [kartena/Proj4Leaflet#116]
We are trying to get the leaflet-proj-refactor branch to work in an npm environment using Leaflet 1.0.0-rc but proj4 requires its own version of leaflet which is set to ~0.7.0 in package.json. proj4leaflet.js consequently loads the wrong leaflet version (from his own node_modules folder) and overwrites the 1.0.0 version with ~0.7.0

**Comment by semone** [comment]
That is not good! 
Will #117 fix this issue for you? Just fixed it and tried quickly locally with Browserify seems to work for me with the PR.
