### ISSUE TITLE
Support World Robinson projection (EPSG:54030)

### ISSUE THREAD

**Issue by PBrockmann** [kartena/Proj4Leaflet#118]
"All major projections are supported ..." but World Robinson does not seem to be possible
(http://spatialreference.org/ref/esri/54030/).

Could someone share an example on this widely used projection (or Natural Earth projection) ?

I get a:
`**uncaught exception: EPSG:54030**`

**Comment by semone** [comment]
Do you have some code showing what you are trying to do?

**Comment by PBrockmann** [comment]
Yes sure. Look at:
[https://gist.github.com/PBrockmann/be22880b33a9bf2f72c48ba03ba576c4#file-choropleth_projection-html](url)

This code works for a "molleweide" projection but I have been able to specify a "robinson" projection (neither a "natural earth" projection).

` var crs = new L.Proj.CRS('ESRI:53009',  '+proj=moll +lon_0=0 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs', 
     {resolutions: [65536, 32768, 16384, 8192, 4096, 2048]
});

var map = L.map('map', {
    crs: crs,
    center: [0, 0]
});`

**Comment by semone** [comment]
Proj4Leaflet uses [Proj4js](http://proj4js.org/) which doesn't support robinson projection.
Your issue seems to be the same as this:  https://github.com/proj4js/proj4js/issues/161

**Comment by PBrockmann** [comment]
The documentation let me think that it was possible since it is written that Proj4Leaflet "supports all commonly used projections" and you can find this projection in many scientific articles from IPCC reports for example. Robinson projection is actually the recommended projection for global maps in those reports.
Finaly, do you know how to add it  ? Or them with the "Natural Earth projection" ?

**Comment by perliedman** [comment]
@PBrockmann as @semone said, this is an upstream issue in Proj4js that Proj4Leaflet uses. To add it, support has to be added in Proj4js. According to [a comment in the issues linked above](https://github.com/proj4js/proj4js/issues/161#issuecomment-154452507), adding it probably isn't that hard.

One can of course argue about what constitutes "commonly used", but you're at least the first one to ask about a missing projection since the start of Proj4Leaflet five years ago!

**Comment by bowerth** [comment]
@perliedman it seems the Robinson projection has been added to proj4js: https://github.com/proj4js/proj4js/blob/master/lib/projections/robin.js
