### ISSUE TITLE
Use with release candidates (Leaflet 1.0.0-rc3 ...)

### ISSUE THREAD

**Issue by jerryhall** [kartena/Proj4Leaflet#119]
Is it safe to assume I can use the 1.0-beta.1 version with the subsequent release candidates eg 1.0.0-rc3? 
Thanks!

**Comment by jgravois** [comment]
the maintainers of this repo have tagged a [1.0.0-beta.2](https://github.com/kartena/Proj4Leaflet/releases/tag/1.0.0-beta.2) version, but we're still referencing beta.1 in an app that loads leaflet `1.0.0-rc.3` and it seems to work just fine.

http://esri.github.io/esri-leaflet/examples/non-mercator-projection.html

**Comment by semone** [comment]
I will take a look at the `leaflet 1.0.0-rc.3` and confirm that it works. 
Seems to work in @jgravois case to use `leaflet 1.0.0-rc.3` with the `proj4leaflet 1.0.0-beta.1` version  🙂

**Comment by jerryhall** [comment]
Awesome thank you both!

**Comment by semone** [comment]
No worries! 

I didn't see any errors when testing it out, the test runs and the examples works as they should. 

I have created a PR here #120 which hopefully will be merged soon

**Comment by pthorin** [comment]
The PR is merged, sorry it took so long.
