### ISSUE TITLE
How to extend tile area?

### ISSUE THREAD

**Issue by joongtang** [kartena/Proj4Leaflet#121]
Hello ^^
I want to extend map area like this

![image](https://cloud.githubusercontent.com/assets/6409795/17920294/b1e73e4a-6a0e-11e6-84b9-c78f77ce2643.png)

so I write code like this

```
var crs = new L.Proj.CRS('EPSG:5181',
  '+proj=tmerc +lat_0=38 +lon_0=127 +k=1 +x_0=200000 +y_0=500000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs',
  {
    resolutions: [2048, 1024, 512, 256, 128, 64, 32, 16, 8, 4, 2, 1, 0.5, 0.25],
    origin: [-30000, -60000],
    bounds: L.bounds([-30000-Math.pow(2,19)*2, -60000-Math.pow(2, 19)*2], [-30000+Math.pow(2,19)*3, -60000+Math.pow(2, 19)*3])
  }
);
```

but this code does not work properly.
Did I do something wrong?
Thanks

**Comment by perliedman** [comment]
Hi!

I'm not sure I understand the question here. Are you trying to add more zoom levels, or are you trying to change the bounds of the tile set?

In any case, it's actually hard to tell anything without knowing more about the tileset you're using. The bounds you configure must of course align with the actual bounds of the tile set, and the same goes for resolution/scale.

**Comment by joongtang** [comment]
I want to change the bounds of tile set.
Using tile set is being used "tms-tiled" example at leaflet-proj-refactor branch.
How to know or calculate the bounds of tile set like above?
Thanks ^^

**Comment by joongtang** [comment]
Hello~, I want to change the bounds of the tile set, again.
This map is daum map in south korea.
I trying to expand bounds like below.

![tobe](https://user-images.githubusercontent.com/6409795/30041675-fe78495c-9226-11e7-8e22-203c6146db81.png)

but I cound'nt.

```
L.Proj.CRS.Daum = new L.Proj.CRS(
  'EPSG:5181',
  '+proj=tmerc +lat_0=38 +lon_0=127 +k=1 +x_0=200000 +y_0=500000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs',
  {
    resolutions: [2048, 1024, 512, 256, 128, 64, 32, 16, 8, 4, 2, 1, 0.5, 0.25],
    origin: [-30000, -60000],
                        // West                  // South                    // East                  // North
    //bounds: L.bounds([-30000-Math.pow(2,19)*2, -60000-Math.pow(2, 19)*2], [-30000+Math.pow(2,19)*3, -60000+Math.pow(2, 19)*3])

    bounds: L.bounds([-30000-Math.pow(2,19)*4, -60000], [-30000+Math.pow(2,19)*5, -60000+Math.pow(2,19)*5])
  }
);
```
I want to set South to -60000-Math.pow(2, 19)*2, not -6000.
However, if I set the south to -60000-Math.pow (2, 19) * 2, like below.

![asis](https://user-images.githubusercontent.com/6409795/30041664-de68c506-9226-11e7-9c03-44986c24e2c8.png)

Here is test page url : [http://k-tmsproviders.codenori.com/examples/indexDaum.html](http://k-tmsproviders.codenori.com/examples/indexDaum.html)
modified Korean Tms Provider github url : [https://github.com/joongtang/Leaflet.KoreanTmsProviders](https://github.com/joongtang/Leaflet.KoreanTmsProviders)

thanks ^^

**Comment by perliedman** [comment]
Looking at this again, I think the problem is that the TMS origin will always be the `bounds` min coordinate, not the same origin as you specify in `origin`; so, when using TMS, different `origin` and `bounds` minimums will likely trip you up.

I'm not 100% certain, and can't really verify either since the sample code is gone.

(As an aside, prefer to use sites like jsfiddle or codepen where the code doesn't go away as easily - it's a bit frustrating as a maintainer when example code goes away, and it's really hard to make sense of most issues without a running code example.)
