### ISSUE TITLE
Problems with OGC:CRS84

### ISSUE THREAD

**Issue by torfsen** [kartena/Proj4Leaflet#128]
I'm having trouble with displaying one of my GeoJSON files using Proj4Leaflet  (ckan/ckanext-geoview#51). The [GeoJSON file](https://raw.githubusercontent.com/wo-ist-markt/wo-ist-markt.github.io/master/cities/karlsruhe.json) specifies its CRS as follows:
```
 "crs": {
        "properties": {
            "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
        },
        "type": "name"
},
```
which seems to be the correct way according to the [GeoJSON 2008 spec](http://geojson.org/geojson-spec.html#named-crs).

When I'm trying to use that JSON with Proj4Leaflet's [`L.Proj.GeoJSON`](https://kartena.github.io/Proj4Leaflet/api/#l-proj-geojson), I'm getting the following error:
```
uncaught exception: No projection definition for code OGC:CRS84
```
The documentation of `L.Proj.GeoJSON` says
> The relevant Proj4 definition should be defined directly via proj4.defs before loading the GeoJSON object. If it is not, Proj4leaflet will throw an error.

Indeed, it seems that `OGC:CRS84` is not one of the default projections provided by Proj4js:
```
>> Object.keys(proj4.defs)
Array [ "EPSG:4326", "EPSG:4269", "EPSG:3857", "WGS84", "EPSG:3785", "GOOGLE", "EPSG:900913", "EPSG:102113" ]
```
I'm rather new to GIS, and still confused about a lot of things, but it seems that [`CRS84` is just `WGS84` but with `lon, lat` order instead of `lat, lon`](http://gis.stackexchange.com/a/124703/48264). However, the 2016 GeoJSON specification ([RFC 7946](https://tools.ietf.org/html/rfc7946)) [says](https://tools.ietf.org/html/rfc7946#section-4): 

>  The coordinate reference system for all GeoJSON coordinates is a
   geographic coordinate reference system, using the World Geodetic
   System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units
   of decimal degrees.  This is equivalent to the coordinate reference
   system identified by the Open Geospatial Consortium (OGC) URN
   urn:ogc:def:crs:OGC::CRS84. 

My data's coordinates are in `lon, lat` format, and I can't change that or the CRS-declaration in the file (the file is provided by a 3rd party).

What's the correct way to fix this problem? Do I need to add a definition for `OGC:CRS84` as the documentation of `L.Proj.GeoJSON` says? If so, where I can I find the information for the definition string? For most projections, [spatialreference.org](http://spatialreference.org) has Proj4 definitions, but I couldn't find `OGC:CRS84` there.

We're using Leaflet 0.7.7 and proj4leaflet 0.7.2.

**Comment by perliedman** [comment]
Hi,

I'm not 100% sure, but I think you will be fine if you do:

```
proj4.defs['OGC:CRS84'] = proj4.defs['EPSG:4326'];
```

That is, I think the parser will always assume coordinates are in lon/lat order, so it's safe to assume CRS84 and EPSG:4326 is the same for this purpose. Note that I haven't actually tried this, though!

**Comment by torfsen** [comment]
Thanks, @perliedman, this does seem to fix the issue!

Do you think that this alias should be included in proj4leaflet, given that proj4leaflet provides `L.Proj.GeoJSON` and the RFC explicitly mentions that CRS? Or would proj4js be a better place?

**Comment by perliedman** [comment]
Great to hear it helped!

I think it would be a bad idea to modify Proj4's defs inside Proj4leaflet, so Proj4 might be better, although I would guess they are conservative on adding more static defs.

**Comment by torfsen** [comment]
OK. I'll suggest it with the proj4j folks, then. Thanks again for your help!
