### ISSUE TITLE
Using proj4leaflet with typescript

### ISSUE THREAD

**Issue by magloire** [kartena/Proj4Leaflet#131]
I am using leaflet in an ionic 2 / angular 2 project. So far it works well; now I need to use EPSG:25832 and came accross this project but don't know how to use it with typescript. I know it's not really related to the project itself, but it would be wonderful if anyone could help. Thanks.

**Comment by sivesind** [comment]
It works fine with EPSG:25833, which seems close to your demand. The resolutions in the following incomplete example are custom, so you need to adapt to your mapserver/map. We use webpack to pack the app, but your app may use something else and therefore use different imports/require-statements.

`   //http://leafletjs.com/
    let L = require('leaflet');

    //https://github.com/Esri/esri-leaflet
    let esri = require('esri-leaflet');

    //https://github.com/aratcliffe/Leaflet.contextmenu, extender L.Map med .ContextMenu
    require('leaflet-contextmenu');

    //proj4leaflet include
    L.Proj = require('proj4leaflet');

    private mapRef;
    private crs;

        //from https://esri.github.io/esri-leaflet/examples/non-mercator-projection.html
        // since leaflet is bundled into the browserify package it won't be able to detect where the images
        // solution is to point it to where you host the the leaflet images yourself
        L.Icon.Default.imagePath = '/node_modules/leaflet/dist/images/';


        //crs
        this.crs = new L.Proj.CRS('EPSG:25833',
            '+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs',
            {
                resolutions: [
                    21674.7100160867, 10837.35500804335, 5418.677504021675, 2709.3387520108377,
                    1354.6693760054188, 677.3346880027094, 338.6673440013547,
                    169.33367200067735, 84.66683600033868, 42.33341800016934,
                    21.16670900008467, 10.583354500042335, 5.291677250021167,
                    2.6458386250105836, 1.3229193125052918, 0.6614596562526459,
                    0.33072982812632296, 0.16536491406316148
                ],
                origin: [-2500000.0, 9045984.0]
            });

        //create map
        this.mapRef = new L.Map('map', {
            crs: this.crs
        });

        esri.tiledMapLayer({
            url: "http://our.custom.mapserver/MapServer",
            tileSize: 512 //our customsize, default is 256
        }).addTo(this.mapRef);

        this.mapRef.setView([59.12374, 10.19107], 13);
`

**Comment by perliedman** [comment]
I don't think there should be anything particular regarding using Proj4Leaflet in TypeScript - it should work like any other Leaflet plugin. I'm not aware of any typescript definitions for Proj4Leaflet.

**Comment by magloire** [comment]
Sorry for disturbing you again :-) 
But I am kind of desparate; I have been to include proj4leaflet by use "declare var L;" on the top of my typescript file. so this line work without any error:

 this.map = L.map('mapid', {
         attributionControl:false,
         crs: new L.Proj.CRS('EPSG:25832','+proj=utm +zone=32 +ellps=GRS80 +units=m +no_defs')
      });

But one: 

this.map.setView([711974.83999999997,6180619.5],13);

cause an error, with the output below:

error_handler.js:53 TypeError: Cannot read property '13' of undefined
    at NewClass.scale (proj4leaflet.js:118)
    at NewClass.latLngToPoint (leaflet-src.js:2056)
    at NewClass.project (leaflet-src.js:3174)
    at NewClass._getNewPixelOrigin (leaflet-src.js:3665)
    at NewClass._move (leaflet-src.js:3413)
    at NewClass._resetView (leaflet-src.js:3378)
    at NewClass.setView (leaflet-src.js:2470)
    at location.ts:173
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (ng_zone.js:227)

I have included leaflet in the project dependencies in package.json, but proj4leaflet is calling its own leaflet-src.js file. Could it be the issue? If so how can force it to use the leaflet included in the project?

I hope it's not a stupid question. Thanks.

**Comment by pthorin** [comment]
I have removed leaflet from the dependencies in package.json, it's scheduled to be included in 1.0.1 (#134), so that should solve that (if there in fact is any problem). 

It looks like you might be having problems because you haven't set any resolutions in your crs.

**Comment by magloire** [comment]
I have added resolutions as in the example above from @sivesind and it solved the issue.

let crs = new L.Proj.CRS('EPSG:25833','+proj=utm +zone=33 +ellps=GRS80 +units=m +no_defs',
                                 {
                        resolutions: [
                            21674.7100160867, 10837.35500804335, 5418.677504021675, 2709.3387520108377,
                            1354.6693760054188, 677.3346880027094, 338.6673440013547,
                            169.33367200067735, 84.66683600033868, 42.33341800016934,
                            21.16670900008467, 10.583354500042335, 5.291677250021167,
                            2.6458386250105836, 1.3229193125052918, 0.6614596562526459,
                            0.33072982812632296, 0.16536491406316148
                        ]
                    }
               );
       this.map = new L.map('mapid', {
         attributionControl:false
        ,crs: crs
      });

    let osm = new L.tileLayer(osmUrl, {minZoom: 12, maxZoom: 30, attribution: osmAttrib});		

    	
       this.map.locate({setView: true, maxZoom:19});
      
       this.map.addLayer(osm);
       
       this.map.on('click',(e: L.MouseEvent)=>{console.log('clicked on ' + e.latlng); });

     output: clicked on LatLng(55.72447, 12.37962)

    Shouldn´t e.latlng be logged in the new projection? but I am still getting coordinates in the default projection. is there something I am doing wrong? I am new at doing maps, excuse me if the questions are stupid.

**Comment by sivesind** [comment]
I think you always work  in decimal degrees, wgs84. Read up on the framework :-)

**Comment by pthorin** [comment]
You get the coordinates for your projection by using crs.project which takes a LatLng (what you get from the mouse event) and returns a L.Point in projected units. See http://leafletjs.com/reference.html#icrs-project
