### ISSUE TITLE
Update bower.json

### ISSUE THREAD

**Issue by wiibaa** [kartena/Proj4Leaflet#133]
First congratulations on your recent release,

but it seems that you omitted to update the bower.json that still reference to leaflet 0.7.x.
Can you please quick fix it.

Edit: by the way: is the leaflet-proj-refactor branch still needed or can master be used now ?

**Comment by pthorin** [comment]
My bad, I will fix it for you!



On Wed, Jan 25, 2017 at 9:10 PM +0100, "Philippe Weber" <notifications@github.com<mailto:notifications@github.com>> wrote:


First congratulations on your recent release,

but it seems that you omitted to update the bower.json that still reference to leaflet 0.7.x.
Can you please quick fix it.

**Comment by pthorin** [comment]
It's in review in #134 

The leaflet-proj-refactor branch should not be used anymore.

**Comment by pthorin** [comment]
Fixed in #134

**Comment by wiibaa** [comment]
Sorry but can you also tag 1.0.1 in git, otherwise it's not usable from bower

**Comment by pthorin** [comment]
Done!
