### ISSUE TITLE
[bug] Pinch-zoom on mobile

### ISSUE THREAD

**Issue by ktgis** [kartena/Proj4Leaflet#135]
- tag: [0.7.2](https://github.com/kartena/Proj4Leaflet/tree/0.7.2) version works fine..
- **[master](https://github.com/kartena/Proj4Leaflet)** version has a pinch-zoom problem

# 1. mobile browser

https://github.com/kartena/Proj4Leaflet/blob/master/examples/osm-tiled/index.html

# 2. zoom-control '-' button click

![zoom](https://cloud.githubusercontent.com/assets/24908579/22454408/f3d9baac-e7c8-11e6-9b76-9188947ef8c4.png) 

# 3. pinch-zoom in 
![Image of pinch](https://maxcdn.icons8.com/windows8/PNG/26/User_Interface/pinch-26.png)

# 4. 
![zoom2](https://cloud.githubusercontent.com/assets/24908579/22454459/50ceb4ec-e7c9-11e6-8b0d-797cd7198a2d.png)

**Comment by dekkiri** [comment]
With this issue, It works fine on desktop browsers but it matters on mobile browser. You can reproduce same situation like below.
1. Zoom out the map to the max zoom level('-' control disabled(gray))
2. Pinch out the map again then the screen changes like picture above 4.

I've tried on device iOS, Android but the result is same.
