### ISSUE TITLE
Use with npm

### ISSUE THREAD

**Issue by dylanparry** [kartena/Proj4Leaflet#137]
Hi,

I've installed both Leaflet and Proj4Leaflet in my npm project, but I'm having trouble figuring out how to use Proj4Leaflet in this set up.

In previous versions, I'd import Leaflet (as L), then import the CRS object from Proj4Leaflet and use it directly, but that doesn't seem to work now.

The error I'm getting is shown in the screenshot below:

![error](https://cloud.githubusercontent.com/assets/3692873/22694632/e04af1be-ed3f-11e6-9112-5e38b04d4b05.png)

Can anyone tell me the correct way of using Leaflet and Proj4Leaflet in my npm project so I no longer get these errors? I'm currently bundling everything together with Webpack, so I'd rather not have to add extra script tags to the page unless absolutely necessary as the intention is to create one JS file that contains all of my map stuff.

Thanks,

Dylan

**Comment by perliedman** [comment]
Hi Dylan,
thanks for taking the time to reporting this issue.

I can't say for certain what's going on without seeing some running code, but Proj4Leaflet is designed to work with NPM/Browserify/Webpack, so in theory what you're trying to do in the code should work.

I haven't personally used the latest release with NPM/Browserify, so it might be that some error have snuck in there. The first thing I would try is to step through Proj4Leaflet's UMD wrapper, to check that it's actually requiring Leaflet properly. In particular, you could check with a debugger what happens around this line: https://github.com/kartena/Proj4Leaflet/blob/master/src/proj4leaflet.js#L8

From the error above, it looks like Leaflet's namespace `L` might not be properly intialized for Proj4Leaflet.

**Comment by dylanparry** [comment]
Hi,

I think actually it's something I'm doing wrong. I'm using Jest to run some tests, and as part of that I'm mocking Leaflet, which of course results in Proj4Leaflet not being able to extend it properly as it's not being mocked correctly.

Thanks for your help though! I'll close this issue now as I'm pretty convinced it's not being caused by a problem in Proj4Leaflet itself.
