### ISSUE TITLE
Using tiles with Mollweide projection?

### ISSUE THREAD

**Issue by apsheronets** [kartena/Proj4Leaflet#155]
Hey there.

I'm making a map about a very northern country using Mollweide projection with `new L.Proj.CRS('ESRI:54009', '+proj=moll +lon_0=60 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs',)`

http://dump.bitcheese.net/files/dyxyjup/2018-01-22-022206_1151x426_scrot.png

Looks much better than Merkator, but little boring because of no tiles.
I saw an example of using tiles with Mollweide projection on openlayers.org:
http://dump.bitcheese.net/files/vykehun/2018-01-22-022313_963x567_scrot.png

But I can't figure out how to use tiles with proj4leaflet. This is my best try:
http://dump.bitcheese.net/files/nanysoj/2018-01-22-022220_414x389_scrot.png

Is that even possible?

**Comment by pthorin** [comment]
Not sure quite what you mean. 
Yes, Proj4Leaflet is well suited for tiled maps, since it uses Leaflet, but you would need a map server or such to provide the tiles. 
Do you have some code you could put up on jsfiddle or such to explain what you mean?

**Comment by perliedman** [comment]
Closing since because of inactivity and no clear issue.
