### ISSUE TITLE
Leaflet Projection Help

### ISSUE THREAD

**Issue by mohammedzamakhan** [kartena/Proj4Leaflet#157]
Currently I am not using proj4leaflet, and just using imageOverlay to show the map, and I get the values in meters which I use to display the imageOverlay between the bounds [0, 60] and [60, 0].

Currently I am using L.CRS.EPSG4326, but I think I should be using your library proj4leaflet to project this instead. But since I am new to this projections, I am really confused what I could be doing here.

![screen shot 2018-08-16 at 12 40 44 pm](https://user-images.githubusercontent.com/2327532/44225196-71985900-a152-11e8-89df-ce459b5f9fe8.png)

**Comment by perliedman** [comment]
Hi,
from your description, it sounds like you're not using an official coordinate system, but rather a meters based system that is adapted to your particular imagery, right?

For such cases, you're probably better off using Leaflet's built-in [L.CRS.Simple](https://leafletjs.com/reference-1.3.2.html#crs-l-crs-simple]. There is a tutorial on how to use it here: https://leafletjs.com/examples/crs-simple/crs-simple.html; I think there might be some other tutorials on the net as well, although I haven't used them myself.
