### ISSUE TITLE
Reproject Leaflet TileLayer

### ISSUE THREAD

**Issue by Toso82** [kartena/Proj4Leaflet#167]
I use latest version of leaflet 1.5.1. I know than can reproject WMS layer but if i want to change project of TileLayer like Google Maps or OpenStreet.. It is possible to do this?

**Comment by perliedman** [comment]
No, Proj4Leaflet can't do raster reprojection, which I think is what you want. The purpose of the plugin is to support other projections than those built into Leaflet.
