### ISSUE TITLE
Question: Leaflet 1.7.1 support (or any higher versions than 1.0.3)

### ISSUE THREAD

**Issue by floriankorn** [kartena/Proj4Leaflet#178]
First of all, thank you for this wonderful package which enables the use of different projections in Leaflet.

Right now Proj4Leaflet uses Leaflet 1.0.3.
Will there be any updates for a Leaflet 1.7.1 support or any newer Leaflet versions?

Or is this project terminated and only usable with Leaflet 1.0.3?

I am using Leaflet 1.7.1 for several projects and step down to an older version for different Packages like Proj4Leaflet.

Happy for any answers and information!

Thank you

**Comment by perliedman** [comment]
To my knowledge, proj4leaflet works with latest Leaflet as well. Don't remember the exact latest version I've used it with, but definitely much later than 1.0.3, it's just that the examples aren't updated.
