### ISSUE TITLE
Proj4Leaflet doc detail/examples

### ISSUE THREAD

**Issue by bennlich** [kartena/Proj4Leaflet#46]
Should the proj4leaflet docs be a little more detailed regarding uses of the lib? Someone asked a seemingly straightforward question on gis exchange: http://gis.stackexchange.com/questions/55043/reprojecting-coordinates-and-geojson-in-leaflet. It apparently isn't obvious to him/her after reading the Proj4Leaflet docs whether Proj4Leaflet can be used to project a vector layer onto tiles in a different coordinate system. Is this the sort of thing that should be covered in the docs? (It's not obvious to me either, actually. Maybe it's more obvious to someone more experienced with projection in slippymap clients?)

**Comment by Olgagr** [comment]
I agree. I'm trying to use this plugin but first and foremost I can't make any of the example in docs working. For example I copied this example from docs:

```
var map = L.map('map', {
          center: [57.74, 11.94],
          zoom: 2048,
          crs: new L.Proj.CRS('EPSG:2400',
            '+lon_0=15.808277777799999 +lat_0=0.0 +k=1.0 +x_0=1500000.0 ' +
            '+y_0=0.0 +proj=tmerc +ellps=bessel +units=m ' +
            '+towgs84=414.1,41.3,603.1,-0.855,2.141,-7.023,0 +no_defs',
            {
              resolutions: [8192, 4096, 2048] // 3 example zoom level resolutions
            }
          ),
          continuousWorld: true,
          worldCopyJump: false
      });

var osmUrl='http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
var osmAttrib='Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors';

      L.tileLayer(osmUrl, {
        maxZoom: 2048,
        attribution: osmAttrib
      }).addTo(map);
```
The tile is not loading at all. No errors, I just see empty map without tile loaded.

I tried to modify zoom levels. I changed:

```
resolutions: [32, 16, 8, 4, 2, 1, 0.5]
```

map zoom level ```zoom: 4``` and tile maxZoom ```maxZoom: 32```. Now, I get a lot of errors in console:
```
-12518.png:1 GET http://b.tile.openstreetmap.org/4/2479/-12518.png 404 (Not Found)
-12516.png:1 GET http://c.tile.openstreetmap.org/4/2482/-12516.png 404 (Not Found)
-12518.png:1 GET http://b.tile.openstreetmap.org/4/2482/-12518.png 404 (Not Found)
```

Can somebody provide a working example with loading tiles ?

**Comment by perliedman** [comment]
@Olgagr hi, OpenStreetMap's tiles are in EPSG:3857 projection, spherical mercator, which is also Leaflet's default projection. If you try to get them while another projection is configured, like in your example above, it will not work.

If you want another projection, you have to find a tile set which uses that projection.

**Comment by perliedman** [comment]
Also closing this issue, http://kartena.github.io/Proj4Leaflet/ is pretty friendly. If we need specific improvements, open new, specific issues.
