### ISSUE TITLE
"Walking" map with custom projection

### ISSUE THREAD

**Issue by kvolleberg** [kartena/Proj4Leaflet#59]
I have made two very simple map setups (based on "https://github.com/bartvde/PDOK-Leaflet". Both maps show more or less the same area. Panning is bounded by  "setMaxBounds". One map uses default Leaflet projection, the other map uses the RD projection (EPSG 28992).

Data can be found here: https://dl.dropboxusercontent.com/u/8713747/walking_maps.zip

When zooming in and/or panning through the map, I notice strange behaviour on the map with RD-projection. It looks like it's related to browser size and map zoomlevel, but effects are different in different browsers and differend window sizes.

In case setMaxBounds is not called (so the user can pan to anywhere), 'walking' does not occur either.

It does not occur for the map with default projection, so I assume it has to do with Proj4Leaflet. 

Cheers, Koen

**Comment by perliedman** [comment]
This long-standing issue has finally been fixed in latest Leaflet master: https://github.com/Leaflet/Leaflet/issues/4077
