### ISSUE TITLE
Cannot add proj4.defs in a node environment (browserify)

### ISSUE THREAD

**Issue by Casen** [kartena/Proj4Leaflet#79]
Not much more to say than that. Proj4leaflet requires proj4 internally, passing it to a factory function. This prevents a user from defining a new projection somewhere down in their code. Perhaps we could add "defs" to the proj4leaflet api?

**Comment by rob-murray** [comment]
Yes, this works fine with Browserify, maybe something like
```
require('proj4leaflet')
proj4 = require('proj4')
proj4.defs({your crs})
```

As mentioned, check there is only one `proj4` in your browserified output and/or `npm dedupe`.

**Comment by perliedman** [comment]
@rob-murray yes, good advice. Thanks for sharing!
