### ISSUE TITLE
Creating Layer without data but with options

### ISSUE THREAD

**Issue by FileNotFound** [kartena/Proj4Leaflet#87]
Hi,
your library really helped me out as my GeoJSON is in strange crs.
But now i need to create a Layer with onEachFeature function and add data later - with "normal" GeoJSON it works like this:

```
var jsonLayer = L.geoJson (null, {
    onEachFeature: function(feature,layer) {
        ...
    }
});
```

And I can do `jsonLayer.addData(someData)` later. To my knowledge there is no way to add the options-object later.
Doing the same with L.Proj.geoJson  throws `Uncaught Error: Invalid GeoJSON object.`.
Is there any way to solve this?

**Comment by perliedman** [comment]
This should have been fixed by #77, please tell us if this is still an issue and we'll consider re-opening.
