### ISSUE TITLE
problem in positioning when zoom

### ISSUE THREAD

**Issue by giammaweb** [kartena/Proj4Leaflet#89]
Hello, i'm new to leaflet.
i have problems when zooming.

the page set the center not where i positioned the mouse pointer or the selection square.

i have tried the new version L.TileLayer and the deprecated version new L.Proj.TileLayer.TMS and several combinations of parameters (pass parameters in my projection or in WGS84)

the deprecated version seems to work a little better, but not always fine.

I have published an example here:
http://mappe-t.comune.modena.it/prove/demo_leaflet/leaflet_tms.html

http://mappe-t.comune.modena.it/prove/demo_leaflet/leaflet_tms_deprecated.html

thank you for the help

**Comment by sookoll** [comment]
Confirm, with EPSG:3301. This issue exists in 2014, but back then, leaflet 0.8 was under development and leaflet-proj4 development branch was fixed. Right now there doesn't seems to have fixed branch.

**Comment by perliedman** [comment]
@sookoll this is very likely an issue with your configuration. If you provide a running example, it might be possible to examine.

**Comment by sookoll** [comment]
Yes You are correct. With leaflet-beta2 version it works correctly. I didn't made mistake in crs configuration from CRS.TMS to CRS. Thanks.
