### ISSUE TITLE
Leaflet 1.0-beta1 compatibility

### ISSUE THREAD

**Issue by IvanSanchez** [kartena/Proj4Leaflet#90]
Some users of Leaflet 1.0-beta1 are complaining that Proj4leaflet only works with 0.7.3. See Leaflet/Leaflet#3731

**Comment by perliedman** [comment]
There is a branch for 1.0 here: https://github.com/kartena/proj4leaflet/tree/leaflet-proj-refactor. We should probably verify it against beta1, since it was developed quite a while ago, and also make sure to include this in the docs.

**Comment by chronixlo** [comment]
The 1.0 branch doesn't have the TMS function but it can be copypasted from master. Seems to work :+1:

**Comment by perliedman** [comment]
I think that is deliberate, since TMS should work without Proj4Leaflet's hack in Leaflet 1.0. That is, you shouldn't have to use `L.Proj.CRS.TMS` any longer, you can just use CRS and set `tms: true` on the `TileLayer`.

**Comment by semone** [comment]
The branch is now verified against beta and updated!

**Comment by jgravois** [comment]
> The branch is now verified against beta and updated!

awesome!  do ya'll plan on tagging a version?  we'd love to reference something official in one of our own published [samples](http://esri.github.io/esri-leaflet/examples/non-mercator-projection.html).

**Comment by semone** [comment]
The verified branch is the leaflet-proj-refactor which should work with Leaflet 1.0-beta. Since the changes form Leaflet 0.7 -> 1.0 affects Proj4Leaflet alot there won't be one branch supporting both. When Leaflet 1.0 is stable and not in beta anymore  there will be a new version out of Proj4Leaflet. 

If you are using Leaflet 0.7.x there is a tagged version which should work for you:
https://github.com/kartena/Proj4Leaflet/releases

Maybe i missunderstood your question?!

**Comment by jgravois** [comment]
thanks for your response.  since Leaflet 1.0.0beta1 is locked now, i was suggesting that it would be helpful if you could tag an actual compatible version (as opposed to pointing people at a live branch) even if your own release is a beta too.

http://github.com/Esri/esri-leaflet/releases

**Comment by semone** [comment]
Now I follow! Good suggestion, I have now fixed that, actually I didn't know about the pre-release feature, you learn new stuff everyday :smiley:

**Comment by chronixlo** [comment]
I don't have a demo for this but going from 1.0 beta to latest master broke pinch zooming. WGS84 proj works fine so I'm assuming it's a proj issue. Can anyone confirm?

**Comment by semone** [comment]
I think this is related to issue #97?

**Comment by chronixlo** [comment]
Oh jeez sorry :D Somehow missed it

**Comment by sivesind** [comment]
@semone Thx for the great work on Proj4Leaflet! Any chance of you publishing the 1.0.0-beta.2 version to npm?

**Comment by sivesind** [comment]
Also, the version of proj4leaflet (set in package.json) in branch `leaflet-proj-refactor` is set to `0.7.0`. I guess it should be `1.0.0-beta.2` or something along that line?

**Comment by semone** [comment]
hi @sivesind  #120 has the latest rc-3 which I hope someone will be able to look at and merge in. It has the correct version in package.json and that one is the one I hope we publish to npm. Will that be okey for you or do you specifically need the beta for some reason? :smile:

**Comment by sivesind** [comment]
RC3 where everything is fixed sounds great! I just need a proj4leaflet version compatible with leaflet@1.0.0-rc-3, since we use esri-leaflet@2.0.2 depending on it. If proj4leaflet@1.0.0-rc3 gets to npm it would be perfect :-) 

Is it @pthorin the one who can merge? Do you have a guess on when this might be merged and published to npm? Keep up the great work!

**Comment by semone** [comment]
@perliedman is the one who should have the credit for the great work! 

@pthorin can merge, I can merge as well but would like a pair of eyes on what I have done :)

**Comment by sivesind** [comment]
@semone Well, happy mergin, really looking forward to see it in npm :-) I've pulled your branch, will test it here :-)

@perliedman Thank you for your great work!

**Comment by pthorin** [comment]
@sivesind I have merged #120, and am looking into publishing a new npm version, but I want to fix #109 first. 

Sorry for taking so long.

**Comment by sivesind** [comment]
@pthorin no apologies needed! I'm just happy proj4leaflet exists, because of you excellent people:-) Keep up the good work! If I find any bugs I'll try to contribute, we have an in-house GIS expert that may assist me.

**Comment by bhaskarvk** [comment]
Hi guys any updates on this ? Leaflet 1.x has been stable now for quite some time. And also thanks for all the work on this guys.

**Comment by pthorin** [comment]
Closed in 1.0.0 (#126).
