### ISSUE TITLE
Wrong condition for Node/CommonJS environment check

### ISSUE THREAD

**Issue by jkordas** [kartena/Proj4Leaflet#93]
In lines 6,7 from file `src/proj4leaflet.js`

```javascript
} else if (typeof module !== 'undefined') {
		// Node/CommonJS
```
when using *jasmine* and angular *ngMock*, `module` variable is defined. As a result Proj4Leaflet is initialized as if it was executed in node envorinment instead of browser.
Is it possible to change this condition?

Underscore uses:
```javascript
typeof module !== 'undefined' && module.exports
```
for that purpose (http://stackoverflow.com/a/5197219).

**Comment by semone** [comment]
This is related to PR #75. I think changing the condition is possible and will look into that. Adding the <code>module.exports</code> condition might not work for some CommonJS environments (see *Adding CommonJS* here http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/)

**Comment by semone** [comment]
PR #75 is now merged which should take care of this!

**Comment by perliedman** [comment]
@semone closing this, then?
