### ISSUE TITLE
gh-pages / web site

### ISSUE THREAD

**Issue by perliedman** [kartena/Proj4Leaflet#94]
I've run away and made a website for Proj4Leaflet. It more or less replaces the current README, which should be significantly shortened to avoid duplication, if we want to use the website.

The code for the new site is here: https://github.com/perliedman/Proj4Leaflet/tree/gh-pages, and, perhaps more interesting, here's a preview of what the site looks like: http://www.liedman.net/Proj4Leaflet/

There's probably typos and maybe missing information in there, but in general I hope this is a large improvement over the state of the current README and docs. It also makes it a bit easier to write even better docs/tutorials/whatever in the future.

Side note: I couldn't make this a PR, since there's no `gh-pages` branch to pull this into in the main repo :)

**Comment by semone** [comment]
Really, really nice! I took the freedom to change the font since it looked weird in Chrome for Windows.

**Comment by perliedman** [comment]
:+1:
