### ISSUE TITLE
Zoom beyond level 5 issue EPSG:3978

### ISSUE THREAD

**Issue by prushforth** [kartena/Proj4Leaflet#95]
Hi,

I am just trying to use your project with the Leaflet 1.0 beta 1 via the leaflet-proj-refactor branch.

I have a map layer here http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT_CBCT_GEOM_3978/MapServer
which I can view all the way in to zoom level 17 in its built in viewer, here:

http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT3978/MapServer?f=jsapi 

I am trying to set that layer up in Proj4Leaflet.  My code is below.  It works great from zoom=0 to zoom=5. The problem is that when I try to zoom in past level 5, I get the null tiles only.  I am wondering if it is my issue or a bug in Proj4Leaflet ?

Any suggestions as to what to try ?  Thanks.

```
<!DOCTYPE html>
<html>
  <head>
    <title>Proj4Leaflet LCC</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="lib/leaflet.css" />
    <script src="lib/leaflet-src.js"></script>
    <script src="lib/proj4.js"></script>
    <script src="lib/proj4leaflet.js"></script>
  </head>
  <body>
    <div id="map" style="height: 480px; width: 640px"></div>
    <script>
var crs = new L.Proj.CRS('EPSG:3978',
  '+proj=lcc +lat_1=49 +lat_2=77 +lat_0=49 +lon_0=-95 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs',
  {
    resolutions: [
      38364.660062653464, 
      22489.62831258996, 
      13229.193125052918, 
      7937.5158750317505, 
      4630.2175937685215, 
      2645.8386250105837, 
      926.0435187537042, 
      529.1677250021168, 
      317.50063500127004, 
      185.20870375074085, 
      111.12522225044451, 
      66.1459656252646, 
      38.36466006265346, 
      22.48962831258996, 
      7.9375158750317505, 
      4.6302175937685215
    ],
    origin: [-34655800, 39310000]
  }),  
  map = new L.Map('map', {
    crs: crs,
    continuousWorld: true,
    worldCopyJump: false  
  }),
  layer = L.tileLayer('http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT_CBCT_GEOM_3978/MapServer/tile/{z}/{y}/{x}', {
      maxZoom: 17,
      minZoom: 0,
      continuousWorld: true,
      attribution: 'Map data © <a href="http://www.nrcan.gc.ca/earth-sciences/geography/topographic-information/free-data-geogratis/geogratis-web-services/17216#g3">Natural Resources Canada</a>'
}).addTo(map);
  map.setView([45.398043, -75.70683], 5);

    </script>
  </body>
</html>
```

**Comment by prushforth** [comment]
I tried it at Leaflet 0.7.5 + the master branch (without changing proj4.js), with the same results. :-(

**Comment by semone** [comment]
Looks like you are missing two zoom levels in you resolutions.

    resolutions: [
      38364.660062653464, 
      22489.62831258996, 
      13229.193125052918, 
      7937.5158750317505, 
      4630.2175937685215, 
      2645.8386250105837, 
      1587.5031750063501, <- missing 
      926.0435187537042, 
      529.1677250021168, 
      317.50063500127004, 
      185.20870375074085, 
      111.12522225044451, 
      66.1459656252646, 
      38.36466006265346, 
      22.48962831258996, 
      13.229193125052918, <-- missing
      7.9375158750317505, 
      4.6302175937685215
    ],

**Comment by prushforth** [comment]
Thank you!
