### ISSUE TITLE
Overlay custom TMS layer (3857) on another

### ISSUE THREAD

**Issue by pieterdhondt** [kartena/Proj4Leaflet#96]
How can I configure Proj4Leaflet to use [this TMS layer](https://quadridcmmaps.blob.core.windows.net/tynset/basemap.xml) as an overlay on a mapbox layer? I'm not sure how to set the bounds and origin...

This is what I have so far, but it requests the wrong row and columns...:

```javascript
var crs = new L.Proj.CRS.TMS(
            'EPSG:5181',
            '+proj=tmerc +lat_0=38 +lon_0=127 +k=1 +x_0=200000 +y_0=500000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs',
            [-30000, -60000, 494288, 464288],
            { resolutions: [2048, 1024, 512, 256, 128, 64, 32, 16, 8, 4, 2, 1, 0.5, 0.25] }
        );

        var crs_tynset = new L.Proj.CRS.TMS(
            'EPSG:3857',
            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs',
            [-20026376.39, -20048966.10, 20026376.39, 20048966.10],
        {
            resolutions: [5.8135986328125, 2.90679931640625, 1.45339965820313, 0.726699829101563, 0.363349914550781, 0.181674957275391, 0.0908374786376953, 0.0454187393188477]
            //origin: [1199098.1904393, 8923848.54918488]
        });

        var map = L.map('map', {
            crs: crs_tynset,
            continuousWorld: true,
            worldCopyJump: false,
            zoomControl: true
        });

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
            attribution: 'Mapbox',
            maxZoom: 18,
            id: 'mapbox.light',
            accessToken: 'pk.eyJ1IjoicGlldGVyZGhvbmR0IiwiYSI6ImNpZXdvdWx0OTAwMTJzeWx6cTVxZmJ0NjgifQ.lODhO-2hLwWsk8nr12VrCg'
        }).addTo(map);

        new L.TileLayer('http://quadridcmmaps.blob.core.windows.net/tynset/{z}/{x}/{y}.png', {
            tms: true
        }).addTo(map);

        map.setView([62.27597, 10.78254], 0);
```

Anyone knows whats wrong and how to do it right?

**Comment by semone** [comment]
Which Leaflet version are you using?

**Comment by pieterdhondt** [comment]
it's the latest one: http://cdn.leafletjs.com/leaflet-0.7.5/leaflet.js

**Comment by perliedman** [comment]
@pieterdhondt you shouldn't have to use Proj4Leaflet at all in this scenario. EPSG:3857 is the default projection built into Leaflet. Adding the tile layer with `tms` set to true should be enough.

Having said that, I see that you code defines `crs` to EPSG:5181, but seems to never be used, why is that?

Also, this _should_ work in Proj4Leaflet. If you could set up a jsfiddle or similar with this code, it would be easier to test.

**Comment by pieterdhondt** [comment]
I tried without Proj4Leaflet, and the TMS layer shows up, but I didn't find a way to set the origin and bounds of the layer (in projected coordinates) out from what I [have](https://quadridcmmaps.blob.core.windows.net/tynset/basemap.xml). 
Oops, the EPSG:5181 was from [sample code](https://github.com/kartena/Proj4Leaflet/blob/master/examples/tms-tiled/script.js), that shouldn't be there anymore.

I've set up a jsfiddle, so it's easy to modify now: https://jsfiddle.net/pieterdhondt/sdczekfu/

**Comment by perliedman** [comment]
@pieterdhondt right, I see that now. However, this is not going to work.

In Leaflet, the map has one CRS, and all tile layers must share the same CRS. While Mapbox also uses EPSG:3857 projection, they do *not* use TMS, and the origin differs significantly from the origin you have defined.

Actually, I don't think I've seen anyone use EPSG:3857 like the tile set you've linked to. Any particular reason not to put the origin at the lower left corner of the world, like it usually done with TMS in Spherical Mercator?

**Comment by pieterdhondt** [comment]
Okay, so with the current configuration, this is probably not gonna work with Leaflet?
The tileset is coming from infrastructure design software (Novapoint) which always has the origin defined locally. So not so much I can do about that right now.

I did manage to get it working now in OpenLayers3: https://jsfiddle.net/pieterdhondt/auvbfcfc/ 
But it would have been nice to use Leaflet of course :)

**Comment by perliedman** [comment]
@pieterdhondt given that it's actually the same projection, but with different origin, I think it would be technically possible, but you'd have to hack tile layer into using another transformation, so my guess is it would not be worth the trouble.

OpenLayers allows you to do much more when it comes to projections, so it might be the best choice for this problem.
